### ISSUE TITLE
Swag (Any other swag besides Hack for Change Swag?)

### ISSUE THREAD

**Issue by Erin-Denton** [Erin-Denton/Day-of-Civic-Hacking-2015#3]
Swag coming from Hack for Change
Can sponsors give us money for swag?
Can CFA send us swag?

**Comment by Erin-Denton** [comment]
The hack for change swag WILL contain Code for America swag as well. Found out via email.

**Comment by Erin-Denton** [comment]
Andrew will cover 300 round stickers from sticker Mule. Commence designing!

**Comment by akozlik** [comment]
I've ordered 200 rectangle stickers.

**Comment by akozlik** [comment]
@Erin-Denton if there is nothing else we need to do on this you're welcome to close the issue. Thanks!
